### ISSUE TITLE
News section

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/freshrss.org#38]
Hi guys,

the news section on the homepage suggests that there is nothing happening with FreshRSS, as there was no entry within two years.

Its almost sarcastic that a RSS software team has an inactive feed ;-)

What do you think about changing the RSS icon link to https://github.com/FreshRSS/FreshRSS/releases ?

Regards
Kevin

**Comment by Alkarex** [comment]
Indeed, that is a bit of a problem. It is related to the (lack of) updates on https://freshrss.org/blog.html
I do no not think there is any auto-deploy from https://github.com/FreshRSS/freshrss.org/tree/master/blog to https://freshrss.org/blog.html , is there @marienfressinaud ?

Options include:
1. Get some help to maintain a bit more https://freshrss.org
    * See related effort, which somehow stalled https://github.com/FreshRSS/freshrss.org/pull/35 and it would be great to revive it
2. Use GitHub pages (just like for the help) if it makes the updating easier and increases the likelihood that one of us will actually write some updates
3. Use GitHub releases for RSS + news
4. ?

**Comment by Frenzie** [comment]
3 sounds the easiest?

**Comment by kevinpapst** [comment]
GitHub pages would be nice, but from my experience developers tend to be too lazy to blog about their great work ... and no offense, I don't do better ;-)

So I would vote for 3 as well, the news section is still there but users have a higher chance to get infos about new FreshRSS versions. If you add a little more infos to a new release beside the 3 links, it would even feel like a real news feed.

**Comment by marienfressinaud** [comment]
I agree with option 3. Publishing on freshrss.org/blog is not that hard and we could make it automatically deployed in just few hours, but while we don't have any "animator" in the team who might write articles, it is surely easier to redirect users on GitHub release feed 👍

**Comment by Alkarex** [comment]
I have made the latest release a bit more verbose, precisely to experiment with this concept: https://github.com/FreshRSS/FreshRSS/releases/tag/1.9.0

**Comment by kevinpapst** [comment]
The website is currently generated from Pelican and the workflow sounds a bit complicated.
I assume you have to clone Freshican and this repo and then use the config from the README with adjusted RSS URL, generate ... whew. My vote goes for using Github pages, then the community can easily contribute and hosting and instant deployments comes from free (but thats a different topic).

@marienfressinaud I guess you host the main site on your server? 
Could you just add a rewrite rule from https://freshrss.org/feeds/all.atom.xml to https://github.com/FreshRSS/FreshRSS/releases.atom ? Probably better than adjusting the rss link on the website.

**Comment by marienfressinaud** [comment]
Indeed, there are two subjects here:

1. a possible technology change for the website (Pelican -> GitHub Pages)
2. a redirection of feed to GitHub feed

I suggest to stick to the second point for the moment since I think changing Pelican will not address the initial problem (and it would take more time + it would be the opportunity to refresh the design of the website).

About adding a rule from https://freshrss.org/feeds/all.atom.xml to https://github.com/FreshRSS/FreshRSS/releases.atom, I would like to publish an article first to announce this redirection and (maybe?) the suppression of the blog section. But I will, sure! :)

**Comment by marienfressinaud** [comment]
I just published a small article to announce the redirection: https://freshrss.org/redirection-of-news-feed.html

I'll make it effective within the next week. Thanks @kevinpapst for the suggestion!

**Comment by kevinpapst** [comment]
Nice! And thanks for the credits :)

**Comment by marienfressinaud** [comment]
And here it is!

![capture d ecran de 2018-01-11 19-44-03](https://user-images.githubusercontent.com/1436309/34841232-d771d080-f707-11e7-9aea-5399826dd3ba.png)

It could be great to make the release names more explicit because "1.9" is kinda weird. At least something like "Version 1.9" or maybe better "FreshRSS 1.9".

Note that I return a HTTP code 302 so if we want to get `all.atom.xml` url back, we will have no cache issue.

**Comment by Frenzie** [comment]
We should just call them "FreshRSS 1.9.0" etc. I'll go in and edit the titles like that.

![screenshot_2018-01-11_20-07-01](https://user-images.githubusercontent.com/202757/34842216-1bb30e8c-f70b-11e7-98ee-b04f67e6fbd1.png)
![screenshot_2018-01-11_20-07-23](https://user-images.githubusercontent.com/202757/34842217-1bd2ce3e-f70b-11e7-8096-d4ee3d8e32be.png)
